/*This file is auto generated, DO NOT change manually (neither the locales). Use https://docs.google.com/spreadsheets/d/16xG8azk5QMYlgABpbniI6cZnxvQl-pmKUFiR1smQD-I/edit?usp=sharing to generate the whole translation, stringKey file and locales folders*/

/** An example of a title with {{name}} for prop String key EXAMPLE_STORY_TITLE with default value (en) = "Hello {{name}}" */
export const EXAMPLE_STORY_TITLE = "example_story_title";
/** An example of a button label String key EXAMPLE_CHANGE_BUTTON_LABEL with default value (en) = "Modify" */
export const EXAMPLE_CHANGE_BUTTON_LABEL = "example_change_button_label";
/** A counter with {{count}} for prop String key EXAMPLE_COUNTER_COUNT_TEXT with default value (en) = "Never changed language (0)" */
export const EXAMPLE_COUNTER_COUNT_TEXT = "example_counter_count_text";
/** General text ok (used mainly in dialog cta) String key GENERAL_OK with default value (en) = "Okay" */
export const GENERAL_OK = "general_ok";
/** General text cancel (used mainly in dialog cta) String key GENERAL_CANCEL with default value (en) = "Cancel" */
export const GENERAL_CANCEL = "general_cancel";
/** General text next (used in flows to pass to the next page) String key GENERAL_NEXT with default value (en) = "Next" */
export const GENERAL_NEXT = "general_next";
/** General text back (used in flows to return to the previous page) String key GENERAL_BACK with default value (en) = "Back" */
export const GENERAL_BACK = "general_back";
/** General text close (used in flows generally on a close button) String key GENERAL_CLOSE with default value (en) = "Close" */
export const GENERAL_CLOSE = "general_close";
/** Have a prefix text to a timer for an upcoming event String key TIMING_UPCOMING_PREFIX_TIME_TEXT with default value (en) = "Begins in: {{time}}" */
export const TIMING_UPCOMING_PREFIX_TIME_TEXT = "timing_upcoming_prefix_time_text";
/** Have a prefix text to a timer for an ending event String key TIMING_ENDING_PREFIX_TIME_TEXT with default value (en) = "Ends in: {{time}}" */
export const TIMING_ENDING_PREFIX_TIME_TEXT = "timing_ending_prefix_time_text";
/** Indicating that a time has expired String key TIMING_EXPIRED_TEXT with default value (en) = "Expired" */
export const TIMING_EXPIRED_TEXT = "timing_expired_text";
/** General text before the icon to win medal String key GENERAL_WIN_MEDAL_TEXT with default value (en) = "Win" */
export const GENERAL_WIN_MEDAL_TEXT = "general_win_medal_text";
/** General text before the icon to earn prize String key GENERAL_EARN_PRIZE_TEXT with default value (en) = "Earn" */
export const GENERAL_EARN_PRIZE_TEXT = "general_earn_prize_text";
/**  String key LEAGUE_QUALIFICATION_PROMOTION_TITLE with default value (en) = "Congratulations!" */
export const LEAGUE_QUALIFICATION_PROMOTION_TITLE = "league_qualification_promotion_title";
/**  String key LEAGUE_QUALIFICATION_DEMOTION_TITLE with default value (en) = "You?ve been demoted!" */
export const LEAGUE_QUALIFICATION_DEMOTION_TITLE = "league_qualification_demotion_title";
/**  String key LEAGUE_QUALIFICATION_STEADY_TITLE with default value (en) = "You have stayed the course!" */
export const LEAGUE_QUALIFICATION_STEADY_TITLE = "league_qualification_steady_title";
/**  String key LEAGUE_QUALIFICATION_HEADER with default value (en) = "You are qualified for" */
export const LEAGUE_QUALIFICATION_HEADER = "league_qualification_header";
/** General text entry String key PLAY_TILE_ENTRY_TEXT with default value (en) = "Entry" */
export const PLAY_TILE_ENTRY_TEXT = "play_tile_entry_text";
/** General text prize String key PLAY_TILE_PRIZE_TEXT with default value (en) = "Prize" */
export const PLAY_TILE_PRIZE_TEXT = "play_tile_prize_text";
/** The full time format used for countdown  String key TIME_FORMAT_D_H_M_S with default value (en) = "{{days}}d {{hours}}h {{minutes}}m {{seconds}}s" */
export const TIME_FORMAT_D_H_M_S = "time_format_d_h_m_s";
/** The time format used for countdown more than 24 hours String key TIME_FORMAT_D_H_M with default value (en) = "{{days}}d {{hours}}h {{minutes}}m" */
export const TIME_FORMAT_D_H_M = "time_format_d_h_m";
/** The time format used for countdown more than 60 minutes String key TIME_FORMAT_H_M_S with default value (en) = "{{hours}}h {{minutes}}m {{seconds}}s" */
export const TIME_FORMAT_H_M_S = "time_format_h_m_s";
/** The time format used for countdown more than 60 seconds String key TIME_FORMAT_M_S with default value (en) = "{{minutes}}m {{seconds}}s" */
export const TIME_FORMAT_M_S = "time_format_m_s";
/** The time format used for countdown with second suffix String key TIME_FORMAT_S with default value (en) = "{{seconds}}s" */
export const TIME_FORMAT_S = "time_format_s";
/**  String key GENERAL_PLAY with default value (en) = "Play" */
export const GENERAL_PLAY = "general_play";
/**  String key PRIZE_GUARANTEED_TEXT with default value (en) = "Prizes Guaranteed" */
export const PRIZE_GUARANTEED_TEXT = "prize_guaranteed_text";
/** The header of the prize details page String key PRIZE_DETAILS_HEADER with default value (en) = "Prize information" */
export const PRIZE_DETAILS_HEADER = "prize_details_header";
/** The header of the prize details page for modal (shorter version of the prize_details_header) String key PRIZE_DETAILS_HEADER_SHORT with default value (en) = "Prize info" */
export const PRIZE_DETAILS_HEADER_SHORT = "prize_details_header_short";
/** The title used in the prize details screen String key PRIZE_DETAILS_TITLE_VIRTUAL_CURRENCY with default value (en) = "Practice currency" */
export const PRIZE_DETAILS_TITLE_VIRTUAL_CURRENCY = "prize_details_title_virtual_currency";
/** The title used in the prize details screen String key PRIZE_DETAILS_TITLE_TICKETZ with default value (en) = "Ticketz" */
export const PRIZE_DETAILS_TITLE_TICKETZ = "prize_details_title_ticketz";
/** The title used in the prize details screen String key PRIZE_DETAILS_TITLE_BONUS_CASH with default value (en) = "Bonus Cash" */
export const PRIZE_DETAILS_TITLE_BONUS_CASH = "prize_details_title_bonus_cash";
/** The title used in the prize details screen String key PRIZE_DETAILS_TITLE_CASH with default value (en) = "Cash" */
export const PRIZE_DETAILS_TITLE_CASH = "prize_details_title_cash";
/** The description used in the prize details screen String key PRIZE_DETAILS_DESCRIPTION_VIRTUAL_CURRENCY with default value (en) = "Use the practice currency to practice your Skillz!" */
export const PRIZE_DETAILS_DESCRIPTION_VIRTUAL_CURRENCY = "prize_details_description_virtual_currency";
/** The description used in the prize details screen String key PRIZE_DETAILS_DESCRIPTION_TICKETZ with default value (en) = "Trade in your Ticketz for amazing prizes in the Ticketz Store!" */
export const PRIZE_DETAILS_DESCRIPTION_TICKETZ = "prize_details_description_ticketz";
/** The description used in the prize details screen String key PRIZE_DETAILS_DESCRIPTION_BONUS_CASH with default value (en) = "Bonus Cash can be used to pay entry fees and compete for prizes, but cannot be withdrawn." */
export const PRIZE_DETAILS_DESCRIPTION_BONUS_CASH = "prize_details_description_bonus_cash";
/** The description used in the prize details screen String key PRIZE_DETAILS_DESCRIPTION_CASH with default value (en) = "Use your cash winnings to compete in more real prize tournaments!" */
export const PRIZE_DETAILS_DESCRIPTION_CASH = "prize_details_description_cash";
/** The range of rank which the prize applies to String key PRIZE_RANGE_RANK with default value (en) = "{{lower_range, ordinal}} - {{upper_range, ordinal}}" */
export const PRIZE_RANGE_RANK = "prize_range_rank";
/** Indicating in a leaderboard if no player has claimed that slot (ie: nobody in ranked at this position) String key LEADERBOARD_OPEN_SLOT with default value (en) = "Open" */
export const LEADERBOARD_OPEN_SLOT = "leaderboard_open_slot";
/** The copy button title used in share referral info details screen String key SHARE_REFERRAL_INFO_CLIPBOARD_COPY with default value (en) = "Copy" */
export const SHARE_REFERRAL_INFO_CLIPBOARD_COPY = "share_referral_info_clipboard_copy";
/** The the title used in the share referral info screen  String key SHARE_REFERRAL_PROMO_CODE_LABEL with default value (en) = "Share your Promo Code" */
export const SHARE_REFERRAL_PROMO_CODE_LABEL = "share_referral_promo_code_label";
/** The title used in the share referral info screen String key SHARE_REFERRAL_CTA_TEXT with default value (en) = "Share and Redeem" */
export const SHARE_REFERRAL_CTA_TEXT = "share_referral_cta_text";
/** The header title used in leagues ftue screen view String key LEAGUE_FTUE_HEADER with default value (en) = "Introducing Leagues" */
export const LEAGUE_FTUE_HEADER = "league_ftue_header";
/** The title in league ftue screen view String key LEAGUE_FTUE_TITLE with default value (en) = "Earn More Prizes" */
export const LEAGUE_FTUE_TITLE = "league_ftue_title";
/** The prize description label on the league ftue screen view String key LEAGUE_FTUE_PRIZE_POOL with default value (en) = "Prize pool" */
export const LEAGUE_FTUE_PRIZE_POOL = "league_ftue_prize_pool";
/** The accessibility label for an empty player level cell String key ACCESSIBILITY_PLAYER_LEVEL_CELL_EMPTY with default value (en) = "Empty player level" */
export const ACCESSIBILITY_PLAYER_LEVEL_CELL_EMPTY = "accessibility_player_level_cell_empty";
/** The accessibility label for a player level cell with basic information String key ACCESSIBILITY_PLAYER_LEVEL_CELL_INFO with default value (en) = "Player level for {{title}} {{subtitle}}." */
export const ACCESSIBILITY_PLAYER_LEVEL_CELL_INFO = "accessibility_player_level_cell_info";
/** The accessibility label for a player level cell with extended information String key ACCESSIBILITY_PLAYER_LEVEL_CELL_EXTENDED_INFO with default value (en) = "Player level for {{title}} {{subtitle}}. Level {{level_number}}, {{percentage}}% completed." */
export const ACCESSIBILITY_PLAYER_LEVEL_CELL_EXTENDED_INFO = "accessibility_player_level_cell_extended_info";
/** Shown on player level when it obtain the max level String key PLAYER_LEVEL_INFO_MAX with default value (en) = "Max level" */
export const PLAYER_LEVEL_INFO_MAX = "player_level_info_max";
/** Show the progression information of a player's level String key PLAYER_LEVEL_INFO_PROGRESSION with default value (en) = "{{exp_to_next}} XP to Level {{next_level_number}}" */
export const PLAYER_LEVEL_INFO_PROGRESSION = "player_level_info_progression";
/** The total experience of a player's level String key PLAYER_LEVEL_INFO_TOTAL_EXP with default value (en) = "{{total_exp}} Total XP" */
export const PLAYER_LEVEL_INFO_TOTAL_EXP = "player_level_info_total_exp";
/** The accessibility label for the percentage achieved on that level (progress bar visual) String key ACCESSIBILITY_PLAYER_LEVEL_ACHIEVED_INFO with default value (en) = "{{percentage_achieved}}% achieved" */
export const ACCESSIBILITY_PLAYER_LEVEL_ACHIEVED_INFO = "accessibility_player_level_achieved_info";
/** The accessibility of the player's level expanded information String key ACCESSIBILITY_PLAYER_LEVEL_INFO with default value (en) = "Level information : {{info,list}}" */
export const ACCESSIBILITY_PLAYER_LEVEL_INFO = "accessibility_player_level_info";
